### ISSUE TITLE
AUA is always responding with 502s

### ISSUE THREAD

**Issue by HiiroSakaki** [Arcaea-Infinity/ArcaeaUnlimitedAPI#4]
Hi o/

I am a user of AUA via @Awbugl's server (will gladly provide my User-Agent).
As of lately, I'm only getting 502s responses from the API. Is there some modification on how to access the API?

I'm also using this opportunity to ask what are the plans considering Lowiro sunset their official API and released Arcaea Online? AUA will still be maintained?

(Discord Tag if private answer needed: Hiiro#1654)

Thanks a lot for your time!

**Comment by Awbugl** [comment]
Lowiro has blocked the vast majority of accounts for score queries for our main API currently, and I have no way to register accounts automatically for the time being. So AUA will end its service.
